// The Vuetify components the templates use, registered globally by vuetify.js.
//
// Registering all of Vuetify (`import * as components from
// 'vuetify/components'`) put every component and its stylesheet in the bundle,
// used or not. Add a component here when a template starts using it: one that
// is missing renders as an unknown <v-...> element, and Vue warns "Failed to
// resolve component", which the browser checks (tests/e2e) fail on.
//
// MarkdownText puts the VDivider, VTable and VCode classes on plain HTML, so
// those three must stay registered for their styles.
export {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAvatar,
  VBadge,
  VBanner,
  VBottomNavigation,
  VBreadcrumbs,
  VBtn,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardItem,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCode,
  VCol,
  VCombobox,
  VContainer,
  VDatePicker,
  VDefaultsProvider,
  VDivider,
  VEmptyState,
  VExpandTransition,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelText,
  VExpansionPanelTitle,
  VFadeTransition,
  VField,
  VFileInput,
  VForm,
  VIcon,
  VImg,
  VInput,
  VList,
  VListGroup,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VListSubheader,
  VMain,
  VMenu,
  VNavigationDrawer,
  VParallax,
  VProgressCircular,
  VProgressLinear,
  VRow,
  VScaleTransition,
  VScrollYTransition,
  VSelect,
  VSheet,
  VSlider,
  VSlideXReverseTransition,
  VSlideXTransition,
  VSlideYReverseTransition,
  VSlideYTransition,
  VSnackbar,
  VSpacer,
  VSpeedDial,
  VStepper,
  VStepperHeader,
  VStepperItem,
  VStepperWindow,
  VStepperWindowItem,
  VSwitch,
  VTab,
  VTable,
  VTabs,
  VTextarea,
  VTextField,
  VThemeProvider,
  VToolbar,
  VToolbarTitle,
  VTooltip,
  VWindow,
  VWindowItem,
} from 'vuetify/components';
