import js from '@eslint/js';
import globals from 'globals';
import typescript from '@typescript-eslint/eslint-plugin';
import vue from 'eslint-plugin-vue';
import vuetify from 'eslint-plugin-vuetify';

export default [
  {
    ignores: [
      // Generated by nearleyc from imports/parser/grammar.ne (see
      // imports/parser/readme.md): editing it would be lost on the next compile
      'imports/parser/grammar.js',
      // Meteor's own files, and the build contexts and bundles of its Rspack
      // integration (reserved directories, see docs.meteor.com)
      '.meteor/',
      '_build/',
      'public/build-assets/',
      'public/build-chunks/',
      'private/build-assets/',
    ],
  },
  js.configs.recommended,
  // Before the Vue configs: its parser applies to every file, and .vue files
  // take vue-eslint-parser instead
  ...typescript.configs['flat/recommended'],
  ...vue.configs['flat/recommended'],
  ...vuetify.configs['flat/recommended'],
  ...vuetify.configs['flat/recommended-v4'],
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.mocha,
        Assets: 'readonly',
      },
    },
    rules: {
      quotes: ['error', 'single'],
      'vue/prop-name-casing': ['warn', 'camelCase', { ignoreProps: ['_id'] }],
      'vue/block-order': ['error', { order: ['template', 'script', 'style'] }],
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['rspack.config.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
];
