// Vuetify components used in this app's templates, registered explicitly.
//
// This replaces the zer0th:meteor-vuetify-loader build plugin, which scanned
// every .vue file on every rebuild to auto-import these. Listing them here
// keeps Vuetify tree-shaken without paying that per-rebuild cost.
//
// To regenerate after adding a new <v-*> tag, from app/:
//   grep -rhoE "<v-[a-z0-9-]+" imports --include=*.vue | sed 's/^<//' | sort -u \
//     | awk '{n=split($0,a,"-"); s=""; for(i=1;i<=n;i++){s=s toupper(substr(a[i],1,1)) substr(a[i],2)} print s}'

export {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAvatar,
  VBadge,
  VBanner,
  VBottomNavigation,
  VBreadcrumbs,
  VBtn,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VCombobox,
  VContainer,
  VDatePicker,
  VDivider,
  VExpandTransition,
  VExpansionPanel,
  VExpansionPanelContent,
  VExpansionPanelHeader,
  VExpansionPanels,
  VFadeTransition,
  VFileInput,
  VFlex,
  VFooter,
  VForm,
  VIcon,
  VImg,
  VLayout,
  VList,
  VListGroup,
  VListItem,
  VListItemAction,
  VListItemActionText,
  VListItemAvatar,
  VListItemContent,
  VListItemGroup,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VParallax,
  VProgressCircular,
  VProgressLinear,
  VRow,
  VScaleTransition,
  VScrollYTransition,
  VSelect,
  VSheet,
  VSlideXReverseTransition,
  VSlideXTransition,
  VSlideYReverseTransition,
  VSlideYTransition,
  VSlider,
  VSnackbar,
  VSpacer,
  VSpeedDial,
  VStepper,
  VStepperContent,
  VStepperHeader,
  VStepperItems,
  VStepperStep,
  VSubheader,
  VSwitch,
  VTab,
  VTabItem,
  VTabs,
  VTabsItems,
  VTextField,
  VTextarea,
  VThemeProvider,
  VToolbar,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/lib/components';
